# This is where all properties go
# You can define different properties for different environments (ex. demo, dev, prod)

#We will also use flyway. It allows us to manage our DB schema as it evolves

# Connection Details for Database
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
    pool-size: 30

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true

book-cover-api:
  url: "http://bookcover.longitood.com/bookcover"

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
  profiles:
    active: dev

